services:
  loki:
    image: grafana/loki:3.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    profiles: [ observe ]

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:11.3.1
    ports:
      - "3000:3000"
    profiles: [ observe ]

  integrations_tests:
    build:
      context: .
      dockerfile: deployments/tests/Dockerfile
    env_file:
      - .env
    command: >
      "set -x && tracer setup && tracer init --pipeline-name testing \   --run-id test-tag \ && ./test-files/scripts/monitor.sh && \  ./test-files/scripts/track_datasets.sh && sleep 5"
    depends_on:
      db:
        condition: service_healthy
    profiles: [ integrations_tests ]

  parallel_tests:
    build:
      context: .
      dockerfile: deployments/tests/Dockerfile

    deploy:
      replicas: 2

    env_file:
      - .env
    command: >
      "set -x && tracer setup && tracer init --pipeline-name testing \   --run-id parallel-tag \ && ./test-files/scripts/monitor.sh && \  ./test-files/scripts/track_datasets.sh && sleep 5"
    depends_on:
      db:
        condition: service_healthy
    profiles: [ parallel_tests ]

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracer_db
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "tracer_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: [ parallel_tests, integrations_tests ]

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: youngstizy@gmail.com
      PGADMIN_DEFAULT_PASSWORD: incorrect

    profiles: [ integrations_tests ]
