api_key = "<YOUR_API_KEY>"
service_url = "https://app.tracer.bio/api"
process_polling_interval_ms = 20
batch_submission_interval_ms = 5000
aws_profile = "me"
db_url = "postgres://postgres:postgres@db:5432/tracer_db"
